site_name: Assistente de Status de Processo — MVP
site_description: Documentação do MVP (FastAPI + Postgres + Vanna + Ollama + pgvector)
theme:
  name: material
  language: pt-BR

nav:
  - Início: index.md
  - Arquitetura: architecture.md
  - Intenções: intents.md
  - Fluxo NLQ: nlq_flow.md
  - Roadmap: roadmap.md
