version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: pgassistente
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: processos
    ports:
      - "5432:5432"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d